services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.staging:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    networks:
      - web
      - acela-core
  acela-core: # name of the service
    build:
      context: . # the directory containing Docker context (".", meaning the current directory)
      dockerfile: Dockerfile.staging # specify the local Dockerfile
    container_name: acela-core # what to label the container for docker ps
    restart: always # restart if failed, until we stop it ourselves
    env_file:
      - .env.staging
    #external_links:
      #- mongo
    ports:
      - 4569:4569
    networks:
      - acela-core
    environment:
      # MONGO_HOST: mongo:27017
      IPFS_HOST: ipfs:5001
      UPLOAD_PATH: /acela-uploads
    volumes:
      - ./data/acela-uploads:/acela-uploads
  tusd:
    image: tusproject/tusd:v1.9
    command: -s3-bucket mybucket -s3-endpoint http://minio:9000 -host=0.0.0.0 -port=1080 -behind-proxy -max-size 5000000000 -hooks-http http://acela-core:4569/api/v1/tus-callback
    volumes:
      - ./data/tusd-uploads:/data
    networks:
      - acela-core
    ports:
      - 1080:1080
    environment: 
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_REGION: eu-west-1
  minio:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    networks: 
      - acela-core
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "./data/s3-uploads:/data/"
    environment: 
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
  # mongo:
  #   container_name: mongo_acela
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - 27417:27017
  #   networks:
  #     - acela-core
  #   volumes:
  #     - ./data/mongodb:/data/db

volumes:
  tusd:

networks:
  acela-core:
    driver: bridge
    external: false
  web:
    external: true
