FROM node:18.14.2-alpine
WORKDIR /usr/app
COPY package*.json ./
RUN apk add --no-cache git python3 make g++ ffmpeg
RUN npm install
COPY . .
RUN npm run build
CMD ["node","--experimental-specifier-resolution=node", "./dist/index.js"]