FROM node:18.14.2-alpine
WORKDIR /usr/app
COPY package*.json ./
RUN apk add --no-cache git python3 make g++ ffmpeg
RUN npm install && npm install typescript -g
COPY . .
RUN tsc -p tsconfig.json
CMD ["node","--experimental-specifier-resolution=node", "./dist/index.js"]