services:
  acela-core:
    build:
      context: .
      dockerfile: Dockerfile.local # specify the local Dockerfile
    container_name: acela-core
    restart: always
    env_file:
      - .env.local
    ports:
      - 4569:4569
      - 9229:9229
    networks:
      - acela-core
    environment:
      ENV_FILE: .env.local
      IPFS_HOST: ipfs:5001
      UPLOAD_PATH: /acela-uploads
    volumes:
      - ./data/acela-uploads:/acela-uploads
      - .:/usr/app
    depends_on:
      - mongo
  tusd:
    image: tusproject/tusd:v1.9
    command: -s3-bucket mybucket -s3-endpoint http://minio:9000 -host=0.0.0.0 -port=1080 -behind-proxy -max-size 5000000000 -hooks-http http://acela-core:4569/api/v1/tus-callback
    volumes:
      - ./data/tusd-uploads:/data
    networks:
      - acela-core
    ports:
      - 1080:1080
    environment: 
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_REGION: eu-west-1
  minio:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    networks: 
      - acela-core
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "./data/s3-uploads:/data/"
    environment: 
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
  mongo:
    container_name: mongo_acela
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    networks:
      - acela-core
    volumes:
      - ./data/mongodb:/data/db

volumes:
  tusd:

networks:
  acela-core:
    driver: bridge
    external: false
  web:
    external: true
